version: "3"
services:
    pg:
        image: postgres
        container_name: pgdb
        deploy:
            replicas: 1 
            restart_policy:
                condition: on-failure
        ports:
          - "5432:5432"  
        environment:
          - POSTGRES_USER=ariados
          - POSTGRES_PASSWORD=
          - POSTGRES_DB=crawl
        volumes:
          - ./postgres/data:/var/lib/postgresql/data
