DB_NAME = "crawl"
NUM_WORKERS = 100

# db has a limit on number of entries (or max size of payload) for transaction
MAX_ENTRIES_PER_TRANSACTION = 1000

CRAWL_QUEUE_MAX_SIZE = 10000
CRAWL_QUEUE_LOAD_FACTOR = 0.2
CRAWL_QUEUE_MIN_SECONDS = 3
CRAWL_QUEUE_MAX_SECONDS = 10

NEW_LINKS_QUEUE_MAX_SIZE = 10000
NEW_LINKS_QUEUE_LOAD_FACTOR = 0.3
NEW_LINKS_QUEUE_MAX_WAIT_SECONDS = 5

COMPLETED_QUEUE_MAX_SIZE = 10000
COMPLETED_QUEUE_LOAD_FACTOR = 0.3
COMPLETED_QUEUE_MAX_WAIT_SECONDS = 5

BATCH_QUEUE_MAX_SIZE = 2 * NUM_WORKERS

RESULTS_QUEUE_MAX_SIZE = 10000

URL_BATCH_SIZE = 10
URL_BATCH_MAX_WAIT_TIME = 5
