{
 "title": "Ariados",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Constants",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.$prefix.constants.*"
    }
   ]
  },
  {
   "title": "URLs processed per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "target": "stats.$prefix.lambdas.urls.processing"
    }
   ]
  },
  {
   "title": "disk.status.processing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.$prefix.urls.processing"
    }
   ]
  },
  {
   "title": "disk -> memqueue time",
   "type": "singlestat",
   "description": "time to fill memqueue from disk",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "stats.timers.$prefix.insert_into_crawlqueue.mean"
    }
   ]
  },
  {
   "title": "disk.status.waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.$prefix.urls.waiting"
    }
   ]
  },
  {
   "title": "disk.status.completed",
   "type": "singlestat",
   "description": "Number of URLs marked completed in the database",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.$prefix.urls.completed"
    }
   ]
  },
  {
   "title": "mem.waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.$prefix.urls.waiting.in_mem"
    }
   ]
  },
  {
   "title": "Average successful lambdas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "target": "stats.timers.$prefix.golang.invoke.handle_multiple_urls.success.count"
    }
   ]
  },
  {
   "title": "disk.status.failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.$prefix.urls.failed"
    }
   ]
  },
  {
   "title": "Avg Lambda Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.timers.ariados.golang.invoke.handle_multiple_urls.success.mean"
    }
   ]
  },
  {
   "title": "Total succesful lambdas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "target": "stats.timers.$prefix.golang.invoke.handle_multiple_urls.success.count"
    }
   ]
  },
  {
   "title": "Lambda failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "target": "stats.timers.$prefix.golang.invoke.handle_multiple_urls.failure.count"
    }
   ]
  },
  {
   "title": "Active Lambdas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.ariados.lambdas.active"
    }
   ]
  },
  {
   "title": "Invocation time",
   "type": "graph",
   "description": "Amount of time taken for a lambda invocation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "movingAverage(stats.timers.$prefix.golang.invoke.handle_multiple_urls.success.mean_90, 1)"
    },
    {
     "target": "movingAverage(stats.timers.$prefix.lambdas.invocation.failure.mean_90, 1)"
    }
   ]
  },
  {
   "title": "URLs finished",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.ariados.urls.completed, stats.gauges.ariados.urls.failed)"
    }
   ]
  },
  {
   "title": "Crawl Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "movingAverage(stats.$prefix.crawlq.get, 1)"
    },
    {
     "target": "movingAverage(stats.$prefix.crawlq.put, 1)"
    }
   ]
  },
  {
   "title": "Writes To DB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.$prefix.db.insert_batch.mean, 'writesToDB')"
    },
    {
     "target": "alias(stats.timers.$prefix.db.update_batch.mean, 'updatesToDB')"
    }
   ]
  }
 ]
}