version: "3"
services:
    graphite:
        image: graphiteapp/graphite-statsd
        container_name: graphite
        deploy:
            replicas: 1 
            restart_policy:
                condition: on-failure
        ports:
          - "8080:80"  
          - "2003:2003"
          - "2004:2004"
          - "2023:2023"
          - "2024:2024"  
          - "8125:8125/udp"
          - "8126:8126"
        volumes:
          - ./graphite/configs:/opt/graphite/conf
          - ./graphite/data:/opt/graphite/storage
          - ./graphite/statsd_config:/opt/statsd/config
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        links:
          - graphite  
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        ports:
          - "3000:3000"
        volumes:
          - ./grafana:/var/lib/grafana


